"""
Visual Asset Pipeline Orchestrator — Fix #2.

Responsibilities:
1. Accept a validated PresentationArtifact (text already generated by Gemini).
2. Use Visual Decision Layer to identify eligible instructional slides.
3. For each eligible slide, build prompt and invoke Image Generator.
4. Upload resulting image bytes via StorageService and inject an Asset back into the slide.
5. Failure on any individual slide must NOT fail the whole presentation.
6. Return the enriched PresentationArtifact for final validation.

FE receives only the final public URL — provider is fully abstracted.
"""
import uuid
from typing import Any

from app.core.logging import get_logger
from app.schemas.presentation_artifact import PresentationArtifact
from app.services.ai.image_generator import generate_image_bytes
from app.services.ai.visual_decision_layer import build_image_prompt, should_generate_image
from app.services.storage.storage_service import StorageService

logger = get_logger(__name__)

# Backward-compatibility aliases for tests/internal imports
_should_generate_image = should_generate_image
_build_image_prompt = build_image_prompt
_generate_image_bytes = generate_image_bytes


async def enrich_with_images(
    artifact: PresentationArtifact,
    mata_pelajaran: str = "",
    fase: str = "B",
) -> PresentationArtifact:
    """
    Main pipeline entry point.

    Takes a fully text-generated and Pydantic-validated PresentationArtifact,
    enriches eligible slides with actual image assets, and returns the updated artifact.

    Failures are per-slide; one failed image does NOT abort the pipeline.
    The returned artifact is always a valid PresentationArtifact (even if no images were added).
    """
    log = logger.bind(total_slides=len(artifact.slides))
    log.info("Starting visual asset enrichment")

    eligible_slides = [s for s in artifact.slides if should_generate_image(s)]
    log.info("Eligible slides for image generation", count=len(eligible_slides))

    if not eligible_slides:
        log.info("No slides require image generation — returning artifact unchanged")
        return artifact

    # Build a mutable dict representation to inject assets
    artifact_dict: dict[str, Any] = artifact.model_dump(mode="json")
    slides_by_id = {s["id"]: s for s in artifact_dict["slides"]}

    for slide in eligible_slides:
        slide_log = log.bind(slide_id=slide.id, slide_title=slide.title)
        slide_log.info("Generating image for slide")

        try:
            image_prompt = build_image_prompt(slide, mata_pelajaran, fase)
            image_bytes = await generate_image_bytes(image_prompt)

            if image_bytes is None:
                slide_log.warning("Image generation returned no bytes — slide will have empty assets")
                continue

            filename = f"slide-{slide.id}-{uuid.uuid4().hex[:8]}.webp"
            asset_dict = await StorageService.upload_image(
                image_bytes=image_bytes,
                filename=filename,
                alt=slide.title or "Ilustrasi pembelajaran",
                display="fullscreen",  # visual slides → fullscreen display
                content_type="image/webp",
            )

            slides_by_id[slide.id]["assets"].append(asset_dict)
            slide_log.info("Image asset injected", asset_id=asset_dict["id"], url=asset_dict["url"])

        except Exception as exc:
            slide_log.error("Failed to generate/upload image for slide", error=str(exc))
            # Continue with other slides — do not abort the pipeline
            continue

    # Reconstruct from enriched dict — this performs final Pydantic validation
    enriched = PresentationArtifact.model_validate(artifact_dict)
    log.info("Visual asset enrichment complete", total_injected=sum(len(s.assets) for s in enriched.slides))
    return enriched
